### ISSUE TITLE
BNF for reading coordinate pairs

### ISSUE THREAD

**Issue by perlDreamer** [benkasminbullock/Image-SVG-Path#12]
I was reading through the BNF in the path section of the SVG spec, and it doesn't look like Image::SVG::Path supports all the places where you can put spaces and commas between numbers.

I whipped up this test to show what I'm talking about.  I was wondering if you had any thoughts about this?

```
use warnings;
use strict;
use Test::More;
use Test::Exception;
use Image::SVG::Path qw/extract_path_info/;

##Test these different syntaxes to check for path parsing

my @strings = (
    'M150 0 L75 200 L225 200 Z',       'Condensed',
    'M 150 0 L 75 200 L 225 200 Z',    'Whitespace only',
    'M 150 0,L 75 200,L 225 200,Z',    'Commas between commands',
    'M 150 0, L 75 200, L 225 200, Z', 'Commas & whitespace between commands',
    'M 150 0 L 75 200 225 200 Z',      'Repeated command, implicit',
    'M 150 0 L 75,200 225,200 Z',      'Commas inside pairs',
    'M 150 0 L 75,200,225,200 Z',      'Commas inside and between pairs',
    'M 150 0 L 75 200,225 200 Z',      'Commas between pairs only',
    'M 150 0 L 75, 200, 225, 200 Z',   'Commas and whitespace inside and between pairs',
    'M 150 0 L 75 200, 225 200 Z',     'Commas and whitespace between pairs only',
    'M 150 0, L 75 200, 225 200, Z',   'Commas and whitespace between pairs and commands',
);

while(my ($string,$comment) = splice @strings, 0, 2) {
    lives_ok { my @foo = extract_path_info($string); } $comment;
}

done_testing();
```

**Comment by benkasminbullock** [comment]
The SVG path specification gives the following pattern:

comma-wsp:
    (wsp+ comma? wsp*) | (comma wsp*)
comma:
    ","

so I think your examples should match.

I've changed it appropriately.

Thanks.





On 10 June 2016 at 02:46, Colin Kuskie <notifications@github.com> wrote:
>
> I was reading through the BNF in the path section of the SVG spec, and it
doesn't look like Image::SVG::Path supports all the places where you can
put spaces and commas between numbers.
>
> I whipped up this test to show what I'm talking about. I was wondering if
you had any thoughts about this?
>
> use warnings;
> use strict;
> use Test::More;
> use Test::Exception;
> use Image::SVG::Path qw/extract_path_info/;
>
> ##Test these different syntaxes to check for path parsing
>
> my @strings = (
>     'M150 0 L75 200 L225 200 Z',       'Condensed',
>     'M 150 0 L 75 200 L 225 200 Z',    'Whitespace only',
>     'M 150 0,L 75 200,L 225 200,Z',    'Commas between commands',
>     'M 150 0, L 75 200, L 225 200, Z', 'Commas & whitespace between
commands',
>     'M 150 0 L 75 200 225 200 Z',      'Repeated command, implicit',
>     'M 150 0 L 75,200 225,200 Z',      'Commas inside pairs',
>     'M 150 0 L 75,200,225,200 Z',      'Commas inside and between pairs',
>     'M 150 0 L 75 200,225 200 Z',      'Commas between pairs only',
>     'M 150 0 L 75, 200, 225, 200 Z',   'Commas and whitespace inside and
between pairs',
>     'M 150 0 L 75 200, 225 200 Z',     'Commas and whitespace between
pairs only',
>     'M 150 0, L 75 200, 225 200, Z',   'Commas and whitespace between
pairs and commands',
